sudo: required

services:
  - docker
 
before_install:
  - sudo /etc/init.d/postgresql stop
  - cd docker
  - sh redeploy_travis_minimal.sh 
  - sleep 10

script:
  - docker exec -i -t docker_chemireg_1 python /home/chemireg/ChemiRegV2/src/bin/hooks/ChemiRegTester.py
  - sudo docker-compose stop
