sudo: required

language: python

services:
  - docker

install:
  - docker pull ddamerell/chemireg:sgc_rdkit_postgres_bigm
  - docker pull continuumio/anaconda3
  - cd docker/chemireg
  - docker build -t chemireg .
  - cd ../chemireg_postgres
  - docker build -t chemireg_postgres:latest .
  - docker tag chemireg ddamerell/chemireg:latest
  - docker tag chemireg_postgres ddamerell/chemireg:postgres

before_script:
  - docker run -p 127.0.0.1:5432:5432 --name chemireg_postgres -e POSTGRES_PASSWORD=postgres_password -d ddamerell/chemireg:postgres
  - docker run -i -p 127.0.0.1:80:80 -p 127.0.0.1:443:443 -p 127.0.0.1:8888:8888 --name chemireg --link chemireg_postgres -d ddamerell/chemireg:latest

script:
  - echo "Starting tests"
  - docker exec -i -t chemireg python /home/chemireg/src/bin/hooks/create_test_env.py