# Use root/example as user/password credentials
version: '3.1'

services:
  chemireg_postgres:
     image: chemireg_postgres
     restart: always
     ports:
       - "5432:5432"
     command: -c "listen_addresses=*" 
  chemireg:
     image: chemireg:latest
     restart: always
     ports: 
       - "8080:80"
       - "8888:8888"

